name: nodeselector/xcodebuild
description: wrapper for xcodebuild
author: '@nodeselector'
inputs:
  action:
    description: 'The action to perform'
    default: 'build'
  scheme:
    description: 'The scheme to build'
    default: ''
  configuration:
    description: 'The configuration to build'
    default: ''
  destination:
    description: 'The destination to build for'
    default: ''
  workspace:
    description: 'The workspace to build'
    default: ''
  project:
    description: 'The project to build'
    default: ''
  archive-path:
    description: 'The path to the archive'
    default: ''
  app-store-connect-api-key-key-path:
    description: 'The App Store Connect API key'
    default: ''
  app-store-connect-api-key-issuer-id:
    description: 'The App Store Connect API issuer ID'
    default: ''
  app-store-connect-api-key-key-id:
    description: 'The App Store Connect API key ID'
    default: ''
  allow-provisioning-updates:
    description: 'Allow provisioning updates'
    default: 'false'
  allow-device-registration:
    description: 'Allow device registration'
    default: 'false'

runs:
  using: node20
  main: dist/index.js
